# Generated by Django 5.2.12 on 2026-04-22 11:55

import core.models.user
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email', max_length=255, unique=True, verbose_name='email')),
                ('nome', models.CharField(blank=True, help_text='Nome completo', max_length=255, null=True, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, help_text='Telefone', max_length=15, null=True, verbose_name='telefone')),
                ('cargo', models.CharField(blank=True, choices=[('chefe', 'Chefe'), ('gerente', 'Gerente'), ('nutricionista', 'Nutricionista'), ('cuidador', 'Cuidador')], help_text='Cargo do administrador', max_length=50, null=True, verbose_name='cargo')),
                ('data_registro', models.DateField(default=datetime.date.today, help_text='Data de registro', verbose_name='data de registro')),
                ('is_active', models.BooleanField(default=True, help_text='Indica que este usuário está ativo.', verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica que este usuário pode acessar o Admin.', verbose_name='Usuário é da equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            managers=[
                ('objects', core.models.user.AdministradorManager()),
            ],
        ),
    ]
