# Generated by Django 5.2.12 on 2026-05-27 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('quantidade_minima', models.IntegerField(default=0)),
                ('data_ultimo_pedido', models.DateField(blank=True, null=True)),
                ('data_prevista_pedido', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('grau_dependencia', models.IntegerField(default=0)),
                ('status_paciente', models.CharField(blank=True, max_length=45)),
                ('doencas_cronicas', models.TextField(blank=True)),
                ('observacoes', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(max_length=45)),
                ('fabricante', models.CharField(blank=True, max_length=45)),
                ('unidade_medida', models.CharField(blank=True, max_length=45)),
                ('contraindicacoes', models.TextField(blank=True)),
                ('estoque_medicamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='core.estoquemedicamentos')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentosPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(blank=True, max_length=45)),
                ('frequencia', models.CharField(blank=True, max_length=45)),
                ('arquivo_receita', models.CharField(blank=True, max_length=255)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes_medicamento', to='core.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacaoMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_prevista', models.DateTimeField()),
                ('data_hora_aplicacao', models.DateTimeField(blank=True, null=True)),
                ('aplicado', models.BooleanField(default=False)),
                ('motivo_nao_aplicado', models.TextField(blank=True)),
                ('medicamentos_prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='core.medicamentosprescricao')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_solicitada', models.IntegerField()),
                ('data_pedido', models.DateField()),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('medicamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.medicamento')),
                ('medicamentos_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.estoquemedicamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('medico', models.CharField(blank=True, max_length=45)),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='core.fichamedica')),
            ],
        ),
        migrations.AddField(
            model_name='medicamentosprescricao',
            name='prescricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_prescricao', to='core.prescricao'),
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('telefone_responsavel', models.CharField(max_length=14)),
                ('parentesco', models.CharField(blank=True, max_length=40)),
                ('plano_saude', models.CharField(blank=True, max_length=80)),
                ('data_admissao', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('dados_residentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes_gerenciados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45)),
                ('gravidade', models.CharField(blank=True, max_length=45)),
                ('descricao', models.TextField(blank=True)),
                ('providencias', models.TextField(blank=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.residente')),
            ],
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='residente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='core.residente'),
        ),
        migrations.CreateModel(
            name='AvaliacaoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('restricoes_alimentares', models.TextField(blank=True)),
                ('dieta_prescrita', models.TextField(blank=True)),
                ('data_avaliacao', models.DateField()),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_nutricionais', to='core.residente')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45)),
                ('data_hora', models.DateTimeField()),
                ('evolucao', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.residente')),
            ],
        ),
        migrations.CreateModel(
            name='AlergiaRestricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('gravidade', models.CharField(blank=True, max_length=45)),
                ('providencia', models.CharField(blank=True, max_length=45)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias_restricoes', to='core.residente')),
            ],
        ),
        migrations.CreateModel(
            name='RotinaResidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('horario', models.TimeField()),
                ('dias_semana', models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('diario', 'Diário')], max_length=20)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='core.residente')),
            ],
        ),
    ]
