# Generated by Django 5.2.14 on 2026-06-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estoquemedicamentos_fichamedica_medicamento_and_more'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='foto',
            field=models.ForeignKey(blank=True, help_text='Foto de perfil do administrador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.image', verbose_name='foto'),
        ),
    ]
