# Generated by Django 5.2.14 on 2026-08-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_administrador_foto'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='residente',
            name='grau_dependencia',
            field=models.CharField(blank=True, choices=[('grau_1', 'Grau 1 - Independente'), ('grau_2', 'Grau 2 - Necessita auxílio parcial'), ('grau_3', 'Grau 3 - Dependência total')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='residente',
            name='nome_completo',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='residente',
            name='nome_responsavel_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='residente',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='residente',
            name='parentesco_2',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='residente',
            name='quarto',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='residente',
            name='telefone_responsavel_2',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
